// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJywGtmfSfSuDKfc5h7sS3Mlf3vnQojJU',
    appId: '1:557925363472:web:67b1d8dc78317246cd7f95',
    messagingSenderId: '557925363472',
    projectId: 'smsapp-1caaa',
    authDomain: 'smsapp-1caaa.firebaseapp.com',
    databaseURL: 'https://smsapp-1caaa-default-rtdb.firebaseio.com',
    storageBucket: 'smsapp-1caaa.appspot.com',
    measurementId: 'G-C1960YRSQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwSxPAQJoSOt8NGdU9wiYfCsxXN3X2dHI',
    appId: '1:557925363472:android:2b7e1d405e914527cd7f95',
    messagingSenderId: '557925363472',
    projectId: 'smsapp-1caaa',
    databaseURL: 'https://smsapp-1caaa-default-rtdb.firebaseio.com',
    storageBucket: 'smsapp-1caaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9dbkWBSTj3nbBf6S_nEwxv43fmQGfY4',
    appId: '1:557925363472:ios:3dbbc6e4390943c5cd7f95',
    messagingSenderId: '557925363472',
    projectId: 'smsapp-1caaa',
    databaseURL: 'https://smsapp-1caaa-default-rtdb.firebaseio.com',
    storageBucket: 'smsapp-1caaa.appspot.com',
    iosBundleId: 'com.example.sms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj9dbkWBSTj3nbBf6S_nEwxv43fmQGfY4',
    appId: '1:557925363472:ios:f7eeab33a3508381cd7f95',
    messagingSenderId: '557925363472',
    projectId: 'smsapp-1caaa',
    databaseURL: 'https://smsapp-1caaa-default-rtdb.firebaseio.com',
    storageBucket: 'smsapp-1caaa.appspot.com',
    iosBundleId: 'com.example.sms.RunnerTests',
  );
}
